{{- $name := .Release.Name }}
{{- range .Values.storageClasses }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: {{ .name }}
provisioner: rbd.csi.ceph.com
parameters:
    # Specify a string that identifies your cluster. Ceph CSI supports any
    # unique string. When Ceph CSI is deployed by Rook use the Rook namespace,
    # for example "rook-ceph".
    clusterID: {{ $name }}

    # Ceph pool into which the RBD image shall be created
    pool: {{ .pool }}

    # RBD image format. Defaults to "2".
    imageFormat: {{ .imageFormat | default "2" | quote }}

    # RBD image features. Available for imageFormat: "2". CSI RBD currently supports only `layering` feature.
    imageFeatures: {{ .imageFeatures | default "layering" }}

    # The secrets have to contain Ceph admin credentials.
    csi.storage.k8s.io/provisioner-secret-name: {{ .provisionerSecretName | default "csi-rbd-secret" }}
    csi.storage.k8s.io/provisioner-secret-namespace: {{ .provisionerSecretNamespace | default "default" }}
    csi.storage.k8s.io/node-publish-secret-name: {{ .nodePublishSecretName | default "csi-rbd-secret" }}
    csi.storage.k8s.io/node-publish-secret-namespace: {{ .nodePublishSecretNamespace | default "default" }}

    # Ceph users for operating RBD
    adminid: {{ .adminid | default "admin" }}
    userid: {{ .userid | default "kubernetes" }}
    # uncomment the following to use rbd-nbd as mounter on supported nodes
    {{- if .mounter }}
    mounter: {{ .mounter }}
    {{- end }}
reclaimPolicy: {{ .reclaimPolicy | default "Delete" }}
---
{{- end }}
